name: Build and Publish Docs

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
env:
  ROLEPLUS_INTERNAL_URL: https://teslaitstudios.com/References.zip
  ROLEPLUS_INTERNAL_PATH: ${{ github.workspace }}/References
      
jobs:
  build_and_publish_docs:
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2

      - name: Setup Nuget
        uses: NuGet/setup-nuget@v1.0.6
        
      - name: Get Build References
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri https://teslaitstudios.com/References.zip -OutFile ${{ github.workspace }}/References.zip
          Expand-Archive -Path References.zip -DestinationPath ${{ env.ROLEPLUS_INTERNAL_PATH }}
        
      - name: Download DocFX
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install docfx --pre
          
      - name: Run DocFX
        env:
          ROLEPLUS_INTERNAL: ${{ env.ROLEPLUS_INTERNAL_PATH }}
        run: docfx docfx.json; docfx docfx.json
        
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: docs
          build_dir: _site
          keep_history: true
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
